### ISSUE TITLE
Multiple commands produce in Xcode 13.1

### ISSUE THREAD

**Issue by aloveric** [ADSuyi/ADSuyiSDKDemo-iOS-Swift#1]
Multiple commands produce '/Users/xxxx/Library/Developer/Xcode/DerivedData/ADSuyiSDKDemo-iOS-Swift-bmeppfpwkarhetfymkhocutlphau/Build/Products/Debug-iphonesimulator/ADSuyiSDKDemo-iOS-Swift.app/Frameworks/KSAdSDK.framework':
1) That command depends on command in Target 'ADSuyiSDKDemo-iOS-Swift' (project 'ADSuyiSDKDemo-iOS-Swift'): script phase “[CP] Embed Pods Frameworks”
2) That command depends on command in Target 'ADSuyiSDKDemo-iOS-Swift' (project 'ADSuyiSDKDemo-iOS-Swift'): script phase “[CP] Embed Pods Frameworks”

**Comment by iOSRE-Erik** [comment]
> Multiple commands produce '/Users/xxxx/Library/Developer/Xcode/DerivedData/ADSuyiSDKDemo-iOS-Swift-bmeppfpwkarhetfymkhocutlphau/Build/Products/Debug-iphonesimulator/ADSuyiSDKDemo-iOS-Swift.app/Frameworks/KSAdSDK.framework':
> 
> 1. That command depends on command in Target 'ADSuyiSDKDemo-iOS-Swift' (project 'ADSuyiSDKDemo-iOS-Swift'): script phase “[CP] Embed Pods Frameworks”
> 2. That command depends on command in Target 'ADSuyiSDKDemo-iOS-Swift' (project 'ADSuyiSDKDemo-iOS-Swift'): script phase “[CP] Embed Pods Frameworks”

  pod 'ADSuyiSDK/ADSuyiSDKPlatforms/ks'#快手简版
  pod 'ADSuyiSDK/ADSuyiSDKPlatforms/ksfull'#快手内容版本选其一pod install 不需要两个都选择 麻烦注释ksfull 再试下
